# Generated by Django 3.2 on 2023-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=40, null=True)),
                ('character', models.CharField(max_length=40, null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('md5', models.CharField(max_length=32)),
                ('likes', models.IntegerField()),
                ('source', models.IntegerField()),
            ],
        ),
    ]
