# Generated by Django 3.2 on 2023-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='author',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='character',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='hash_sha',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pictures',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pictures',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
