# Generated by Django 3.2 on 2023-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0002_auto_20230808_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='hash_sha',
        ),
        migrations.AddField(
            model_name='pictures',
            name='md5',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
