# Generated by Django 3.2 on 2023-08-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0003_auto_20230809_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='source',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
